export const cardData = [
  {
    id: 1,
    src: "images/netflix.jpg",
    alt: "netflix project image",
    title: "React Netflix Clone",
    description:
      "A Netflix clone made with React and Firebase. Coverage tested with Jest. ",
    webpage: "https://shan-react-netflix-clone.netlify.app/",
    github: "https://github.com/ShannonTJ/react-netflix-clone",
  },
  {
    id: 2,
    src: "images/responsive-site.png",
    alt: "project image",
    title: "Responsive React Site",
    description:
      "A responsive site made with React Router, styled components, and smooth scroll. ",
    webpage: "https://shan-react-responsive-site2.netlify.app/",
    github: "https://github.com/ShannonTJ/react-responsive-site2",
  },
  {
    id: 3,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 4,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 5,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 6,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
];
