export const cardData = [
  {
    id: 1,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 2,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 3,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 4,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 5,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
  {
    id: 6,
    src: "images/svg-5.svg",
    alt: "project image",
    title: "React Netflix Clone",
    description: "This is sample text.",
    webpage: "",
    github: "",
  },
];
